# Use root/example as user/password credentials
version: "3.1"

services:
  # mongo:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example

  # react:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./frontend/public:/public
  #     - ./frontend/src:/src
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true

  # fast:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8000:80
  #   volumes:
  #     - ./backend:/app

  rabbitmq:
    image: rabbitmq:3-management
    hostname: my-rabbit
    ports:
      - 5672:5672
      - 15672:15672

  deepmoji:
    build:
      context: ./deepmoji
      dockerfile: Dockerfile
    volumes:
      - ./deepmoji:/server
